//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_SanPham
    {
        public CAT_SanPham()
        {
            this.EXP_PhieuXuat = new HashSet<EXP_PhieuXuat>();
        }
    
        public int ID_san_pham { get; set; }
        public string Ma_san_pham { get; set; }
        public string Ten_san_pham { get; set; }
        public int ID_nhan_vien { get; set; }
        public int ID_khach_hang { get; set; }
        public decimal Chi_phi_lap_dat { get; set; }
    
        public virtual CAT_KhachHang CAT_KhachHang { get; set; }
        public virtual CAT_NhanVien CAT_NhanVien { get; set; }
        public virtual ICollection<EXP_PhieuXuat> EXP_PhieuXuat { get; set; }
    }
}
