//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhieuNhap
    {
        public LoaiPhieuNhap()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }
    
        public int MaLoaiNhap { get; set; }
        public string TenLoaiNhap { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
