//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKhoDongLucEntities : DbContext
    {
        public QuanLyKhoDongLucEntities()
            : base("name=QuanLyKhoDongLucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAT_KhachHang> CAT_KhachHang { get; set; }
        public DbSet<CAT_NhaCungCap> CAT_NhaCungCap { get; set; }
        public DbSet<CAT_NhanVien> CAT_NhanVien { get; set; }
        public DbSet<CAT_SanPham> CAT_SanPham { get; set; }
        public DbSet<EXP_LoaiXuat> EXP_LoaiXuat { get; set; }
        public DbSet<EXP_PhieuXuat> EXP_PhieuXuat { get; set; }
        public DbSet<EXP_PhieuXuatCT> EXP_PhieuXuatCT { get; set; }
        public DbSet<IMP_LoaiNhap> IMP_LoaiNhap { get; set; }
        public DbSet<IMP_PhieuNhap> IMP_PhieuNhap { get; set; }
        public DbSet<IMP_PhieuNhapCT> IMP_PhieuNhapCT { get; set; }
        public DbSet<STO_KhoVatTu> STO_KhoVatTu { get; set; }
        public DbSet<STO_KhoVatTuCT> STO_KhoVatTuCT { get; set; }
        public DbSet<STO_LoaiVatTu> STO_LoaiVatTu { get; set; }
        public DbSet<STO_NhomVatTu> STO_NhomVatTu { get; set; }
        public DbSet<STO_VatTu> STO_VatTu { get; set; }
        public DbSet<SYS_NguoiDung> SYS_NguoiDung { get; set; }
        public DbSet<SYS_Quyen> SYS_Quyen { get; set; }
        public DbSet<SYS_SuKienNguoiDung> SYS_SuKienNguoiDung { get; set; }
        public DbSet<SYS_VaiTro> SYS_VaiTro { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
