//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKContext : DbContext
    {
        public QLKContext()
            : base("name=QLKContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KhoVatTu> KhoVatTus { get; set; }
        public DbSet<LoaiPhieuNhap> LoaiPhieuNhaps { get; set; }
        public DbSet<LoaiVatTu> LoaiVatTus { get; set; }
        public DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public DbSet<NhomVatTu> NhomVatTus { get; set; }
        public DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public DbSet<PhieuNhapCT> PhieuNhapCTs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VatTu> VatTus { get; set; }
    }
}
