//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_TrangThaiNguoiDung
    {
        public SYS_TrangThaiNguoiDung()
        {
            this.SYS_NguoiDung = new HashSet<SYS_NguoiDung>();
        }
    
        public int ID_trang_thai { get; set; }
        public string Trang_thai { get; set; }
    
        public virtual ICollection<SYS_NguoiDung> SYS_NguoiDung { get; set; }
    }
}
