//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LoaiDieuKhien
    {
        public SYS_LoaiDieuKhien()
        {
            this.SYS_ThuocTinh = new HashSet<SYS_ThuocTinh>();
        }
    
        public int ID_loai { get; set; }
        public string Ky_hieu { get; set; }
        public string Ten_loai { get; set; }
    
        public virtual ICollection<SYS_ThuocTinh> SYS_ThuocTinh { get; set; }
    }
}
