//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCboNhanVien
    {
        public int ID_nhan_vien { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> ID_kho { get; set; }
        public string Ten_kho { get; set; }
    }
}
