//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNguoiDung
    {
        public int ID_nguoi_dung { get; set; }
        public Nullable<int> ID_nhan_vien { get; set; }
        public string Tai_khoan { get; set; }
        public string Ten_day_du { get; set; }
        public Nullable<System.DateTime> Lan_dang_nhap_cuoi { get; set; }
        public Nullable<System.TimeSpan> Thoi_gian_cho { get; set; }
        public int ID_trang_thai { get; set; }
        public string Trang_thai { get; set; }
        public string Nhan_vien { get; set; }
        public string May_tram { get; set; }
    }
}
