//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPhieuNhap
    {
        public string So_chung_tu_goc { get; set; }
        public string Ten_loai_nhap { get; set; }
        public string Ten_nha_cung_cap { get; set; }
        public System.DateTime Ngay_nhap { get; set; }
        public decimal Tong_tien { get; set; }
        public string Nguoi_sua { get; set; }
        public string Nhan_vien_nhap { get; set; }
        public string Nhan_vien_lap { get; set; }
        public int ID_phieu_nhap { get; set; }
        public string Ten_kho { get; set; }
        public System.DateTime Ngay_sua { get; set; }
        public string Trang_thai { get; set; }
        public int ID_kho { get; set; }
        public Nullable<int> ID_nha_cung_cap { get; set; }
        public Nullable<int> ID_nhan_vien_nhap { get; set; }
        public Nullable<int> ID_nhan_vien_lap { get; set; }
        public string Ghi_chu { get; set; }
        public int ID_loai_nhap { get; set; }
        public int Expr1 { get; set; }
        public int ID_nguoi_sua { get; set; }
    }
}
