//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_NhanVien
    {
        public CAT_NhanVien()
        {
            this.CAT_SanPham = new HashSet<CAT_SanPham>();
            this.EXP_PhieuXuat = new HashSet<EXP_PhieuXuat>();
            this.IMP_PhieuNhap = new HashSet<IMP_PhieuNhap>();
        }
    
        public int ID_nhan_vien { get; set; }
        public int ID_kho { get; set; }
        public string Ho_dem { get; set; }
        public string Ten { get; set; }
        public int Gioi_tinh { get; set; }
        public System.DateTime Ngay_sinh { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> Ngay_cap { get; set; }
        public string Noi_cap { get; set; }
        public string Dien_thoai { get; set; }
        public string Dia_chi { get; set; }
        public string Email { get; set; }
        public int Trang_thai { get; set; }
    
        public virtual ICollection<CAT_SanPham> CAT_SanPham { get; set; }
        public virtual ICollection<EXP_PhieuXuat> EXP_PhieuXuat { get; set; }
        public virtual ICollection<IMP_PhieuNhap> IMP_PhieuNhap { get; set; }
    }
}
