//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PhieuNhap
    {
        public IMP_PhieuNhap()
        {
            this.IMP_PhieuNhapCT = new HashSet<IMP_PhieuNhapCT>();
        }
    
        public int ID_phieu_nhap { get; set; }
        public string Ma_hoa_don { get; set; }
        public int ID_loai_nhap { get; set; }
        public int ID_kho { get; set; }
        public int ID_nha_cung_cap { get; set; }
        public int ID_nhan_vien { get; set; }
        public Nullable<int> ID_nhan_vien_nhap { get; set; }
        public System.DateTime Ngay_nhap { get; set; }
        public decimal Tong_tien { get; set; }
        public string Ghi_chu { get; set; }
        public int Trang_thai { get; set; }
        public Nullable<System.DateTime> Ngay_sua { get; set; }
        public Nullable<int> ID_nguoi_sua { get; set; }
    
        public virtual CAT_NhaCungCap CAT_NhaCungCap { get; set; }
        public virtual CAT_NhanVien CAT_NhanVien { get; set; }
        public virtual IMP_LoaiNhap IMP_LoaiNhap { get; set; }
        public virtual STO_KhoVatTu STO_KhoVatTu { get; set; }
        public virtual ICollection<IMP_PhieuNhapCT> IMP_PhieuNhapCT { get; set; }
    }
}
