//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_PhanHe
    {
        public SYS_PhanHe()
        {
            this.SYS_Quyen = new HashSet<SYS_Quyen>();
            this.SYS_SuKienNguoiDung = new HashSet<SYS_SuKienNguoiDung>();
        }
    
        public int ID_phan_he { get; set; }
        public string Phan_he { get; set; }
        public string Mieu_ta { get; set; }
    
        public virtual ICollection<SYS_Quyen> SYS_Quyen { get; set; }
        public virtual ICollection<SYS_SuKienNguoiDung> SYS_SuKienNguoiDung { get; set; }
    }
}
