//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_LoaiXuat
    {
        public EXP_LoaiXuat()
        {
            this.EXP_PhieuXuat = new HashSet<EXP_PhieuXuat>();
        }
    
        public int ID_loai_xuat { get; set; }
        public string Ten_loai_xuat { get; set; }
        public string Ghi_chu { get; set; }
    
        public virtual ICollection<EXP_PhieuXuat> EXP_PhieuXuat { get; set; }
    }
}
