//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapCT
    {
        public string MaPhieuNhap { get; set; }
        public int MaVatTu { get; set; }
        public string DonVi { get; set; }
        public decimal SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
