//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.PhieuNhapCTs = new HashSet<PhieuNhapCT>();
        }
    
        public string MaPhieuNhap { get; set; }
        public int MaLoaiNhap { get; set; }
        public int MaNCC { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public int MaKho { get; set; }
        public int MaNhanVien { get; set; }
    
        public virtual KhoVatTu KhoVatTu { get; set; }
        public virtual LoaiPhieuNhap LoaiPhieuNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual ICollection<PhieuNhapCT> PhieuNhapCTs { get; set; }
    }
}
