//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STO_TonDauKy
    {
        public int ID_ton { get; set; }
        public System.DateTime Ky { get; set; }
        public int ID_nhan_vien { get; set; }
        public int ID_kho { get; set; }
    
        public virtual CAT_NhanVien CAT_NhanVien { get; set; }
        public virtual STO_KhoVatTu STO_KhoVatTu { get; set; }
        public virtual STO_KhoVatTu STO_KhoVatTu1 { get; set; }
    }
}
