//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SuKienNguoiDung
    {
        public int ID_su_kien { get; set; }
        public int ID_nguoi_dung { get; set; }
        public int ID_vai_tro { get; set; }
        public int Su_kien { get; set; }
        public string Noi_dung { get; set; }
        public System.DateTime Thoi_diem { get; set; }
        public string May_tram { get; set; }
    }
}
