//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ThuocTinh
    {
        public SYS_ThuocTinh()
        {
            this.SYS_LoaiDieuKhien = new HashSet<SYS_LoaiDieuKhien>();
            this.SYS_VaiTroQuyen = new HashSet<SYS_VaiTroQuyen>();
        }
    
        public int ID_thuoc_tinh { get; set; }
        public string Ky_hieu { get; set; }
        public string Ten_thuoc_tinh { get; set; }
        public int Loai_gia_tri { get; set; }
    
        public virtual ICollection<SYS_LoaiDieuKhien> SYS_LoaiDieuKhien { get; set; }
        public virtual ICollection<SYS_VaiTroQuyen> SYS_VaiTroQuyen { get; set; }
    }
}
