//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ThongSoHeThong
    {
        public int ID_thong_so { get; set; }
        public int ID_cha { get; set; }
        public string Ma_thong_so { get; set; }
        public string Ten_thong_so { get; set; }
        public string Gia_tri { get; set; }
    }
}
