//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPhieuNhapCT
    {
        public int ID_phieu_nhap { get; set; }
        public int ID_vat_tu { get; set; }
        public double So_luong { get; set; }
        public Nullable<decimal> Don_gia { get; set; }
        public Nullable<double> Chieu_dai { get; set; }
        public Nullable<double> Chieu_rong { get; set; }
        public int ID_nhom_vat_tu { get; set; }
        public string Ten_vat_tu { get; set; }
        public string Ten_loai_vat_tu { get; set; }
        public int ID_loai_vat_tu { get; set; }
    }
}
