//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCboLoaiVatTu
    {
        public int ID_loai_vat_tu { get; set; }
        public string Ten_loai_vat_tu { get; set; }
        public string Ten_nhom_vat_tu { get; set; }
        public int ID_nhom_vat_tu { get; set; }
        public string Ma_nhom_vat_tu { get; set; }
        public string Ma_loai_vat_tu { get; set; }
        public int ID_kho { get; set; }
        public string Ten_kho { get; set; }
        public string Ghi_chu { get; set; }
    }
}
