//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKho_DongLuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_VaiTro
    {
        public SYS_VaiTro()
        {
            this.SYS_VaiTroQuyen = new HashSet<SYS_VaiTroQuyen>();
            this.SYS_NguoiDung = new HashSet<SYS_NguoiDung>();
        }
    
        public int ID_vai_tro { get; set; }
        public string Ten_vai_tro { get; set; }
        public Nullable<int> Mo_ta { get; set; }
    
        public virtual ICollection<SYS_VaiTroQuyen> SYS_VaiTroQuyen { get; set; }
        public virtual ICollection<SYS_NguoiDung> SYS_NguoiDung { get; set; }
    }
}
