//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLK_DongLuc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SSAP {
            get {
                return ((string)(this["SSAP"]));
            }
            set {
                this["SSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("203.162.246.102")]
        public string DS {
            get {
                return ((string)(this["DS"]));
            }
            set {
                this["DS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QuanLyKhoDongLuc")]
        public string DB {
            get {
                return ((string)(this["DB"]));
            }
            set {
                this["DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string UID {
            get {
                return ((string)(this["UID"]));
            }
            set {
                this["UID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Không được để trống")]
        public string NullOrEmpty {
            get {
                return ((string)(this["NullOrEmpty"]));
            }
            set {
                this["NullOrEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ngày tháng không hợp lệ")]
        public string InvalidDate {
            get {
                return ((string)(this["InvalidDate"]));
            }
            set {
                this["InvalidDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thêm dữ liệu không thành công")]
        public string InsertErrorText {
            get {
                return ((string)(this["InsertErrorText"]));
            }
            set {
                this["InsertErrorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Không có thay đổi nào được cập nhật")]
        public string UpdateErrorText {
            get {
                return ((string)(this["UpdateErrorText"]));
            }
            set {
                this["UpdateErrorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xóa dữ liệu không thành công")]
        public string DeleteErrorText {
            get {
                return ((string)(this["DeleteErrorText"]));
            }
            set {
                this["DeleteErrorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bạn có chắc chắn muốn xóa dữ liệu này?")]
        public string DeleteConfirmText {
            get {
                return ((string)(this["DeleteConfirmText"]));
            }
            set {
                this["DeleteConfirmText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Không thể in dữ liệu")]
        public string PrintErrorText {
            get {
                return ((string)(this["PrintErrorText"]));
            }
            set {
                this["PrintErrorText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lỗi thêm dữ liệu")]
        public string InsertErrorCaption {
            get {
                return ((string)(this["InsertErrorCaption"]));
            }
            set {
                this["InsertErrorCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lỗi cập nhật dữ liệu")]
        public string UpdateErrorCaption {
            get {
                return ((string)(this["UpdateErrorCaption"]));
            }
            set {
                this["UpdateErrorCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lỗi xóa dữ liệu")]
        public string DeleteErrorCaption {
            get {
                return ((string)(this["DeleteErrorCaption"]));
            }
            set {
                this["DeleteErrorCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lỗi in dữ liệu")]
        public string PringErrorCaption {
            get {
                return ((string)(this["PringErrorCaption"]));
            }
            set {
                this["PringErrorCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xác nhận xóa dữ liệu")]
        public string DeleteConfirmCaption {
            get {
                return ((string)(this["DeleteConfirmCaption"]));
            }
            set {
                this["DeleteConfirmCaption"] = value;
            }
        }
    }
}
